import { Category, ReferencePhoto } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'portrait',
    name: 'Chân dung',
    description: 'Chụp cận và trung cảnh cá nhân nghệ thuật',
    icon: 'person-outline',
    cover_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['portrait photoshoot', 'candid portraits'],
  },
  {
    id: 'ootd',
    name: 'OOTD / Dáng',
    description: 'Tôn dáng, khoe outfit thời thượng',
    icon: 'shirt-outline',
    cover_image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['ootd streetwear', 'fashion pose'],
  },
  {
    id: 'couple',
    name: 'Đôi lứa',
    description: 'Tư thế cặp đôi tự nhiên, tình cảm',
    icon: 'heart-outline',
    cover_image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['couple aesthetic pose', 'romantic photoshoot'],
  },
  {
    id: 'cafe',
    name: 'Quán Cafe',
    description: 'Lifestyle thư giãn, ngồi bàn ấm cúng',
    icon: 'cafe-outline',
    cover_image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['cafe sitting photoshoot', 'coffee lifestyle'],
  },
  {
    id: 'group',
    name: 'Nhóm bạn',
    description: 'Bố cục chụp nhóm bạn thân và gia đình',
    icon: 'people-outline',
    cover_image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['friends photoshoot', 'squad poses'],
  },
  {
    id: 'travel',
    name: 'Du lịch',
    description: 'Hòa mình vào thiên nhiên và thắng cảnh',
    icon: 'airplane-outline',
    cover_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    sample_queries: ['travel portrait landscape', 'vacation poses'],
  },
];

export const MOCK_REFERENCES: ReferencePhoto[] = [
  {
    id: 'pin-port-1',
    title: 'Góc nghiêng hoàng hôn ấm áp',
    description: 'Nghiêng mặt 15 độ, ánh nắng xiên tạo khối gò má, mắt nhìn xa xăm',
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1080&auto=format&fit=crop&q=85',
    thumbnail_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    category: 'portrait',
    dominant_color: '#E0A96D',
    camera_guidance: {
      shot_type: 'medium_shot',
      recommended_distance_meters: 1.5,
      angle_type: 'eye_level',
      tilt_degrees: 0.0,
      roll_degrees: 0.0,
      focal_length_hint: '2x chân dung xóa phông',
    },
    composition: {
      rule_type: 'rule_of_thirds',
      subject_anchor: 'center',
      power_point_x: 0.5,
      power_point_y: 0.33,
    },
    lighting: {
      light_direction: 'left',
      contrast_level: 'soft',
      dominant_palette: ['#F7D9C4', '#D8A47F', '#8C583E', '#2C1B14'],
      recommended_exposure_ev: 0.3,
      tone_mood: 'warm',
    },
    pose: {
      pose_type: 'portrait_medium',
      is_facing_camera: true,
      head_tilt: 'tilted_right',
      shoulder_angle: 3.5,
      keypoints: [
        { name: 'nose', x: 0.50, y: 0.30 },
        { name: 'left_eye', x: 0.47, y: 0.27 },
        { name: 'right_eye', x: 0.53, y: 0.27 },
        { name: 'left_shoulder', x: 0.38, y: 0.45 },
        { name: 'right_shoulder', x: 0.62, y: 0.45 },
        { name: 'left_elbow', x: 0.34, y: 0.68 },
        { name: 'right_elbow', x: 0.66, y: 0.68 },
        { name: 'left_wrist', x: 0.38, y: 0.86 },
        { name: 'right_wrist', x: 0.62, y: 0.86 },
      ],
      keypoint_connections: [
        [0, 1], [0, 2], [3, 4], [3, 5], [5, 7], [4, 6], [6, 8]
      ],
      summary_instruction: 'Nghiêng nhẹ mặt 15 độ để tôn đường nét xương quai hàm',
    },
    suggested_tips: [
      'Nghiêng nhẹ cằm sang phải 15 độ',
      'Hạ vai xuống thư giãn, tránh gồng cứng',
      'Đứng cách camera khoảng 1.5 mét',
    ],
  },
  {
    id: 'pin-ootd-1',
    title: 'Dáng bước đi đường phố (OOTD)',
    description: 'Chụp góc thấp ngang thắt lưng để chân dài tự nhiên, bước đi chuyển động',
    image_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1080&auto=format&fit=crop&q=85',
    thumbnail_url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&auto=format&fit=crop&q=80',
    category: 'ootd',
    dominant_color: '#F6AD55',
    camera_guidance: {
      shot_type: 'full_body',
      recommended_distance_meters: 2.8,
      angle_type: 'low_angle',
      tilt_degrees: -8.0,
      roll_degrees: 0.0,
      focal_length_hint: '1x góc rộng nhẹ',
    },
    composition: {
      rule_type: 'rule_of_thirds',
      subject_anchor: 'center',
      power_point_x: 0.5,
      power_point_y: 0.25,
    },
    lighting: {
      light_direction: 'front',
      contrast_level: 'high',
      dominant_palette: ['#1A202C', '#CBD5E0', '#ED8936'],
      recommended_exposure_ev: 0.0,
      tone_mood: 'vibrant',
    },
    pose: {
      pose_type: 'standing_full',
      is_facing_camera: true,
      head_tilt: 'neutral',
      shoulder_angle: 0.0,
      keypoints: [
        { name: 'nose', x: 0.50, y: 0.18 },
        { name: 'left_shoulder', x: 0.43, y: 0.25 },
        { name: 'right_shoulder', x: 0.57, y: 0.25 },
        { name: 'left_hip', x: 0.45, y: 0.52 },
        { name: 'right_hip', x: 0.55, y: 0.52 },
        { name: 'left_knee', x: 0.44, y: 0.72 },
        { name: 'right_knee', x: 0.58, y: 0.73 },
        { name: 'left_ankle', x: 0.43, y: 0.92 },
        { name: 'right_ankle', x: 0.60, y: 0.91 },
      ],
      keypoint_connections: [
        [0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7], [6, 8]
      ],
      summary_instruction: 'Bước một chân nhẹ về phía trước, máy ảnh hạ ngang thắt lưng',
    },
    suggested_tips: [
      'Hạ máy ảnh xuống ngang thắt lưng và hơi ngửa máy lên nhẹ',
      'Bước một chân nhẹ về phía trước tạo cảm giác sải bước',
      'Đứng cách camera khoảng 2.8 - 3 mét',
    ],
  },
  {
    id: 'pin-cafe-1',
    title: 'Góc cafe thư giãn bên bàn',
    description: 'Ngồi tựa bàn cafe, hai tay nâng tách nước, góc máy từ trên xuống 15 độ',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1080&auto=format&fit=crop&q=85',
    thumbnail_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&auto=format&fit=crop&q=80',
    category: 'cafe',
    dominant_color: '#7B341E',
    camera_guidance: {
      shot_type: 'medium_shot',
      recommended_distance_meters: 1.2,
      angle_type: 'high_angle',
      tilt_degrees: 15.0,
      roll_degrees: 0.0,
      focal_length_hint: '1x cận cảnh mặt bàn',
    },
    composition: {
      rule_type: 'rule_of_thirds',
      subject_anchor: 'center',
      power_point_x: 0.5,
      power_point_y: 0.35,
    },
    lighting: {
      light_direction: 'top',
      contrast_level: 'medium',
      dominant_palette: ['#4A3728', '#A27045', '#EFE8D8'],
      recommended_exposure_ev: 0.2,
      tone_mood: 'warm',
    },
    pose: {
      pose_type: 'sitting',
      is_facing_camera: true,
      head_tilt: 'tilted_left',
      shoulder_angle: -4.0,
      keypoints: [
        { name: 'nose', x: 0.50, y: 0.25 },
        { name: 'left_shoulder', x: 0.40, y: 0.36 },
        { name: 'right_shoulder', x: 0.60, y: 0.36 },
        { name: 'left_elbow', x: 0.36, y: 0.52 },
        { name: 'right_elbow', x: 0.64, y: 0.52 },
      ],
      keypoint_connections: [
        [0, 1], [0, 2], [1, 3], [2, 4]
      ],
      summary_instruction: 'Ngồi thư giãn, hai tay đặt trên bàn cạnh ly cafe',
    },
    suggested_tips: [
      'Góc máy hơi chúc từ trên xuống 15 độ',
      'Mặt nghiêng nhẹ, nụ cười mỉm tự nhiên',
      'Đứng hoặc ngồi cách camera 1.2 mét',
    ],
  },
];
